services:
  ms-access:
    # Apunta a la imagen publicada en GitHub Container Registry
    image: ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-con-kp-ms-access}

    environment:
      - QUARKUS_HTTP_PORT=${APP_INTERNAL_PORT}

      # Database Configuration
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

      # Quarkus Hibernate
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=${DB_GENERATION:-update}

      # OpenTelemetry
      - OTEL_ENABLED=${OTEL_ENABLED:-false}

    ports:
      - "${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}"

    networks:
      - nt_microservices
    restart: unless-stopped

networks:
  nt_microservices:
    external: true
